apps/blog/urls.py
from django.urls import path

from apps.blog import views

urlpatterns = [
    # 首页加载更多
    path("more/<int:pagenum>/", views.more, name='more'),
    # 文章列表
    path('article_list/<str:key>/<str:unique_id>/', views.article_list, name='article_list'),
    path('article_list/<str:key>/<str:unique_id>/<int:num>/', views.article_list, name='article_list'),
    # 文章详情
    path('article_detail/<str:unique_id>/', views.article_detail, name='article_detail'),
    # 时间轴
    path('time_axis/', views.time_axis, name='time_axis'),
    # 关于我
    path('about_me/', views.about_me, name='about_me'),
    # 留言
    path('leave_msg/', views.leave_msg, name='leave_msg'),
    # 点赞
    path('like/<int:id>/', views.like, name='like'),
    # 评论
    path("comment/<str:unique_id>/", views.comment, name='comment'),
    path("comment/<str:unique_id>/<int:pid>/", views.comment, name='comment'),
    # 收藏
    path("article_col/<int:aid>/", views.article_col, name='article_col'),
    # 留言
    path("leave_msg/", views.leave_msg, name='leave_msg'),
    # 搜索
    path("search/", views.search, name='search'),
    # 作者信息
    path("author_info/<str:unique_id>/", views.author_info, name='author_info'),
]

apps/user/urls.py
from django.urls import path

from apps.user import views

urlpatterns = [
    # 注册
    path('sign_up/', views.sign_up, name='sign_up'),
    # 登陆
    path('sign_in/', views.sign_in, name='sign_in'),
    # 注销
    path('sign_out/', views.sign_out, name='sign_out'),
    # 用户中心
    path('user/<str:unique_id>/', views.user, name='user'),
    # 用户修改密码
    path('repwd/<str:unique_id>/', views.repwd, name='repwd'),
    # 用户评论记录
    path('comment/<str:unique_id>/', views.comment, name='comment'),
    # 用户删除评论记录
    path('comment_del/<str:unique_id>/', views.comment_del, name='comment_del'),
    # 用户收藏记录
    path('articlecol/<str:unique_id>/', views.articlecol, name='articlecol'),
    # 用户删除收藏记录
    path('articlecol_del/<str:unique_id>/', views.articlecol_del, name='articlecol_del'),
]

newcoder/urls.py
from django.contrib import admin
from django.urls import path, include

# 导入静态文件模块
from django.views.static import serve
# 导入配置文件里的文件上传配置
from django.conf import settings

from apps.blog import views

urlpatterns = [
    # 后台
    path('admin/', admin.site.urls),
    # 应用
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    # 首页
    path('', views.index),
    # 微信验证
    path('MP_verify_hC03z28vx2ij7bpL.txt', views.weixin_auth),
    # 配置富文本的URL
    path('summernote/', include('django_summernote.urls')),
    # 用于上传图片文件
    path('static/', serve, {'document_root': settings.MEDIA_ROOT}),
    # 用于加载静态文件
    path('static/', serve, {'document_root': settings.STATIC_ROOT}),
]

apps/user/models.py
from shortuuid import ShortUUID

from django.db import models
from django.contrib.auth.models import AbstractUser


# 生成8位唯一标识符
class NewUUID(ShortUUID):
    def __init__(self, alphabet=None):
        if alphabet is None:
            alphabet = 'abcdefghijklmnopqrstuvwxyz0123456789'
        super().__init__(alphabet)


# 用户表
class User(AbstractUser):
    nickname = models.CharField(max_length=16, unique=True, null=True, blank=True, verbose_name='昵称')
    birthday = models.DateField(null=True, blank=True, verbose_name="出生年月")
    # 0为男，1为女
    gender = models.IntegerField(choices=((0, "男"), (1, "女")), default=0, verbose_name="性别")
    photo = models.ImageField(upload_to="user/photo", null=True, blank=True, verbose_name='头像')
    phone = models.CharField(max_length=11, unique=True, null=True, blank=True, verbose_name='手机号')
    email = models.EmailField(max_length=100, unique=True, null=True, blank=True, verbose_name='邮箱')
    desc = models.CharField(max_length=140, null=True, blank=True, verbose_name='个人简介')
    addtime = models.DateField(auto_now_add=True, verbose_name='注册日期')
    unique_id = models.CharField(max_length=36, default=NewUUID().random(8), unique=True, verbose_name='唯一标识符')

    class Meta:
        # 指定在admin管理界面中显示中文,表示单数形式的显示
        verbose_name = '用户表'
        # 指定在admin管理界面中显示中文,表示复数形式的显示
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.username


# 用户留言表
class Leavemsg(models.Model):
    content = models.CharField(max_length=140, verbose_name="用户留言")
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='留言用户')
    addtime = models.DateTimeField(auto_now_add=True, verbose_name='留言时间')
    unique_id = models.CharField(max_length=36, default=NewUUID().random(8), unique=True, verbose_name='唯一标识符')

    class Meta:
        verbose_name = '用户留言表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.user.nickname

apps/blog/forms.py
from django import forms


# 添加文章验证
class AddarticleForm(forms.Form):
    title = forms.CharField()
    type = forms.CharField()
    pic = forms.ImageField()
    content = forms.CharField()

apps/blog/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.contrib import messages
from django.db.models import Q

from blog.models import *
from user.models import *

pagesize = 13


# 验证登陆装饰器
def user_login_req(func):
    def inner(request, *args, **kwargs):
        obj = request.session.get('user_id')
        if obj:
            # 已经登录
            return func(request, *args, **kwargs)
        else:
            # 没有登录
            # 判断发送的请求是不是ajax
            # 如果是ajax，则返回一个redirect字符串
            # 表示是一个ajax请求
            if 'XMLHttpRequest' == request.META.get('HTTP_X_REQUESTED_WITH'):
                return HttpResponse('请登录')
            else:
                # 不是ajax请求，是浏览器发送的请求，正常返回登录
                messages.success(request, "请先登录！！！")
                return redirect('/user/sign_in/')

    return inner


# 微信验证
def weixin_auth(request):
    return HttpResponse('hC03z28vx2ij7bpL')


# 首页
def index(request):
    # 默认按时间排序，显示前20
    articles = Article.objects.order_by('-addtime')[:pagesize]
    # 首页轮播，显示前5
    articles_plant = Article.objects.filter(is_plant=1)[:5]
    # 首页置顶，显示前2
    articles_top = Article.objects.filter(is_top=1)[:2]
    return render(request, 'blog/index.html', locals())


# 首页加载更多
def more(request, pagenum):
    articles = Article.objects.order_by("-addtime")[pagenum * pagesize:(pagenum + 1) * pagesize]
    # 判断当前获取的分页是否为空
    if len(articles) > 0:
        # 不为空在做操作,渲染页面
        return render(request, "blog/index_item.html", locals())
    elif len(articles) == 0:
        # 为空返回‘empty’给js
        return HttpResponse("empty")


# 文章列表
def article_list(request, key, unique_id, num=1):
    if key == 'type':
        word = 'type'
        # 根据分类获取类型信息
        type_detail = Type.objects.filter(unique_id=unique_id).first()
        # 分类ID
        name_id = type_detail.unique_id
        # 分类名称
        name_name = type_detail.typename
        # 分类简介
        name_label = type_detail.label
        # 通过分类筛选文章
        articles = Article.objects.filter(type=type_detail).order_by('-addtime')
    else:
        word = 'tag'
        # 根据标签获取类型信息
        tag_detail = Tag.objects.filter(unique_id=unique_id).first()
        # 标签ID
        name_id = tag_detail.unique_id
        # 标签名称
        name_name = tag_detail.tagname
        # 标签简介
        name_label = tag_detail.label
        # 通过标签筛选文章
        articles = Article.objects.filter(tag=tag_detail).order_by('-addtime')
    # 生成分页器
    p = Paginator(articles, 13)
    # 当前页
    page = p.get_page(num)
    # 当前页左边连续的页码号，初始值为空
    left = []
    # 当前页右边连续的页码号，初始值为空
    right = []
    # 标示第 1 页页码后是否需要显示省略号
    left_has_more = False
    # 标示最后一页页码前是否需要显示省略号
    right_has_more = False
    # 标示是否需要显示第 1 页的页码号
    first = False
    # 标示是否需要显示最后一页的页码号
    last = False
    # 获得用户当前请求的页码号
    page_number = page.number
    # 获得分页后的总页数
    total_pages = p.num_pages
    # 获得整个分页页码列表
    page_range = p.page_range
    # 根据当前页码进行判断
    if page_number == 1:
        # 如果用户请求的是第一页的数据，那么当前页左边的不需要数据，因此 left=[]（已默认为空）
        # 此时只要获取当前页右边的连续页码号
        # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 right = [2, 3]
        # 注意这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码
        right = page_range[page_number:page_number + 2]
        if len(right) == 0:
            right = [1]
        # 如果最右边的页码号比最后一页的页码号减去 1 还要小
        # 说明最右边的页码号和最后一页的页码号之间还有其它页码，因此需要显示省略号，通过 right_has_more 来指示
        if right[-1] < total_pages - 1:
            right_has_more = True
        # 如果最右边的页码号比最后一页的页码号小，说明当前页右边的连续页码号中不包含最后一页的页码
        # 所以需要显示最后一页的页码号，通过 last 来指示
        if right[-1] < total_pages:
            last = True
    elif page_number == total_pages:
        # 如果用户请求的是最后一页的数据，那么当前页右边就不需要数据，因此 right=[]（已默认为空）
        # 此时只要获取当前页左边的连续页码号
        # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 left = [2, 3]
        # 这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码
        left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
        # 如果最左边的页码号比第 2 页页码号还大
        # 说明最左边的页码号和第 1 页的页码号之间还有其它页码，因此需要显示省略号，通过 left_has_more 来指示
        if left[0] > 2:
            left_has_more = True
        # 如果最左边的页码号比第 1 页的页码号大，说明当前页左边的连续页码号中不包含第一页的页码
        # 所以需要显示第一页的页码号，通过 first 来指示
        if left[0] > 1:
            first = True
    else:
        # 用户请求的既不是最后一页，也不是第 1 页，则需要获取当前页左右两边的连续页码号
        # 这里只获取了当前页码前后连续两个页码，你可以更改这个数字以获取更多页码
        left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
        right = page_range[page_number:page_number + 2]
        # 是否需要显示最后一页和最后一页前的省略号
        if right[-1] < total_pages - 1:
            right_has_more = True
        if right[-1] < total_pages:
            last = True
        # 是否需要显示第 1 页和第 1 页后的省略号
        if left[0] > 2:
            left_has_more = True
        if left[0] > 1:
            first = True
    return render(request, 'blog/level1_article_list.html', locals())


# 文章详情
def article_detail(request, unique_id):
    # 根据文章id获取文章信息
    article = Article.objects.filter(unique_id=unique_id).first()
    aid = article.id
    # 本篇文章所有标签
    all_tag = article.tag.all()
    # 获取本篇文章的上一篇
    prev_aid = aid - 1
    prev_article = Article.objects.filter(id=prev_aid).first()
    # 获取本篇文章的上一篇
    next_aid = aid + 1
    next_article = Article.objects.filter(id=next_aid).first()
    # 根据文章标签获取相关文章信息
    relevant_article = []
    for i in all_tag:
        article_tag = Article.objects.filter(tag=i.id)
        relevant_article += article_tag
    if len(relevant_article) > 10:
        relevant_article = set(relevant_article[:10])
    # 根据父级字段是否有值来筛选出直接评论文章的评论
    comments = article.comment_set.filter(parent=None).order_by("-addtime")
    # 文章浏览量+1
    # 点击1下+1
    article.count += 1
    # # 注册用户点击才会+1
    # id = request.session.get('user_id')
    # ids = request.session.get('ids')
    # if id:
    #     if ids:
    #         if id in ids:
    #             pass
    #         else:
    #             # 加一操作
    #             article.count += 1
    #             ids.append(id)
    #         # 把新的ids写入到session中
    #         request.session['ids'] = ids
    #     else:
    #         ids = []
    #         ids.append(id)
    #         request.session['ids'] = ids
    #         # 加一操作
    #         article.count += 1
    # else:
    #     pass
    article.save()
    # 获取本文章所有评论
    comments = Comment.objects.filter(article=aid, parent=None).order_by('-addtime')
    comment_num = len(comments)
    return render(request, 'blog/level2_article_detail.html', locals())


# 点赞
@user_login_req
def like(request, id):
    art = Article.objects.get(id=id)
    ids = request.session.get('ids')
    # 在一个会话session中,记录下收藏、点赞的文章id,已经点过一次再点,我们认为是取消这个操作
    if ids:
        if id in ids:
            # 减一操作
            art.like = art.like - 1
            ids.remove(id)
        else:
            # 加一操作
            art.like = art.like + 1
            ids.append(id)
        # 把新的ids写入到session中
        request.session['ids'] = ids
    else:
        ids = []
        ids.append(id)
        request.session['ids'] = ids
        # 加一操作
        art.like = art.like + 1
    art.save()
    # 返回我们最新的点赞次数
    return HttpResponse(str(art.like))


# 评论
@user_login_req
def comment(request, unique_id, pid=0):
    # 从session中去拿登录用户的id
    uid = request.session.get("user_id")
    # 把一个文章评论插入到数据库中
    user = User.objects.get(unique_id=uid)
    article = Article.objects.get(unique_id=unique_id)
    content = request.POST.get("content", '')
    if content == '':
        messages.success(request, "评论不能为空")
        return redirect("/blog/article_detail/{}/".format(unique_id))
    if pid:
        # 根据model多了一个父评论字段,我们这里也要增加一个新字段
        parent = Comment.objects.get(id=pid)
    else:
        parent = None
    # 把数据保存到数据表中
    Comment.objects.create(user=user, article=article, content=content, parent=parent, unique_id=NewUUID().random(8))
    return redirect("/blog/article_detail/{}/".format(unique_id))


# 收藏
@user_login_req
def article_col(request, aid):
    uid = request.session.get("user_id")
    user = User.objects.get(unique_id=uid)
    article = Article.objects.get(id=aid)
    col = Articlecol.objects.filter(user=user, article=article).count()
    # 判断当前文章是否收藏
    if col == 0:
        Articlecol.objects.create(user=user, article=article, unique_id=NewUUID().random(8))
        return HttpResponse("1")
    else:
        return HttpResponse("0")


# 时间轴
def time_axis(request):
    article_time = Article.objects.all().order_by('-addtime')
    return render(request, 'blog/level1_time_axis.html', locals())


# 关于我
def about_me(request):
    return render(request, 'blog/level1_about_me.html', locals())


# 留言
def leave_msg(request):
    msgs = Leavemsg.objects.all().order_by('-addtime')
    msg_num = len(msgs)
    if request.method == "GET":
        return render(request, 'blog/level1_leave_msg.html', locals())
    if request.method == 'POST':
        uid = request.session.get("user_id")
        user = User.objects.get(unique_id=uid)
        content = request.POST.get("content", '')
        if content == '':
            messages.success(request, "留言不能为空")
            return redirect("/blog/leave_msg/")
        Leavemsg.objects.create(user=user, content=content)
        return redirect("/blog/leave_msg/")


# 搜索
@user_login_req
def search(request):
    keyword = request.POST.get('keyboard', '')
    if keyword == '':
        messages.success(request, "搜索关键词不能为空")
        return redirect("/")
    articles = Article.objects.filter(Q(title__icontains=keyword) | Q(author__nickname__icontains=keyword))
    articles_num = len(articles)
    return render(request, 'blog/level3_search.html', locals())


# 作者信息
@user_login_req
def author_info(request, unique_id):
    author = User.objects.get(unique_id=unique_id)
    return render(request, 'blog/level4_author_info.html', locals())

templates/blog/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    新码农
{% endblock %}

{% block css %}
    <link href="{% static 'css/more.css' %}" rel="stylesheet">
{% endblock %}

{% block main %}
    <article>

        {% if messages %}
            <script>
                {% for msg in messages %}
                    alert('{{ msg.message }}');
                {% endfor %}
            </script>
        {% endif %}

        {#首页轮播区开始#}
        <div class="picsbox">
            {#轮播开始#}
            <div class="banner">
                <div id="banner" class="fader">
                    {% for item in articles_plant %}
                        <li class="slide">
                            <a href="{% url 'blog:article_detail' item.unique_id %}" target="_blank">
                                <img src="{% static item.pic.name %}">
                                <span class="imginfo">{{ item.title }}</span>
                            </a>
                        </li>
                    {% endfor %}
                    <div class="fader_controls">
                        <div class="page prev" data-target="prev">&lsaquo;</div>
                        <div class="page next" data-target="next">&rsaquo;</div>
                        <ul class="pager_list">
                        </ul>
                    </div>
                </div>
            </div>
            {#轮播结束#}

            {#置顶文章开始#}
            <div class="toppic">
                {% for item in articles_top %}
                    <li>
                        <a href="{% url 'blog:article_detail' item.unique_id %}" target="_blank">
                            <i><img src="{% static item.pic.name %}"></i>
                            <h2>{{ item.title }}</h2>
                            <span>{{ item.type.typename }}</span>
                        </a>
                    </li>
                {% endfor %}
            </div>
            {#置顶文章结束#}
        </div>
        {#首页轮播区结束#}

        {#背景图#}
        <div class="blank"></div>
        {#背景图#}

        {#首页文章列表开始#}
        <div class="blogsbox">
            <div class="itemlist">
                {% for item in articles %}
                    <div class="blogs" data-scroll-reveal="enter bottom over 1s">
                        <h3 class="blogtitle">
                            <a target="_blank" href="{% url 'blog:article_detail' item.unique_id %}">
                                {{ item.title }}
                            </a>
                        </h3>
                        <span class="blogpic">
                            <a target="_blank" href="{% url 'blog:article_detail' item.unique_id %}">
                                <img src="{% static item.pic.name %}" alt="">
                            </a>
                        </span>
                        <p class="blogtext">{{ item.label }}</p>
                        <div class="bloginfo">
                            <ul>
                                <li class="author">
                                    <a href="{% url 'blog:author_info' item.author.unique_id %}" target="_blank">
                                        {{ item.author.nickname }}
                                    </a>
                                </li>
                                <li class="lmname">
                                    <a href="{% url 'blog:article_list' 'type' item.type.unique_id %}"
                                       target="_blank">{{ item.type.typename }}</a>
                                </li>
                                <li class="timer">{{ item.addtime }}</li>
                                <li class="view"><span>{{ item.count }}</span>已阅读</li>
                                <li class="like">{{ item.like }}</li>
                            </ul>
                        </div>
                    </div>
                {% empty %}
                    <h1>系统在维护中，请下次访问！</h1>
                {% endfor %}
            </div>
            {#首页加载更多按钮#}
            <div class="blogs">
                <p><input type="button" value="点击加载更多" class="more"></p>
            </div>
            {#首页加载更多按钮#}
        </div>
        {#首页文章列表结束#}

        {#侧边栏#}
        {% include 'blog/base_sidebar_wz.html' %}
        {#侧边栏#}

    </article>

    {#首页加载更多ajax#}
    <script>
        {#如果是第一页就是0#}
        var pagenum = 0;
        {#注册more点击监听器#}
        $(".more").click(function () {
            pagenum++;
            {#向服务器发送加载更多请求,jquery封装的ajax#}
            $.get("/blog/more/" + pagenum + "/", function (data) {
                {#根据返回的数据,判断是否为空,为空就alert()#}
                if (data == "empty") {
                    alert("所有文章已加载完毕!");
                } else {
                    {#不为空,展示出来返回的html字符串#}
                    $(".itemlist").append(data);
                }
            });
        });
    </script>
    {#首页加载更多ajax#}

{% endblock %}

templates/blog/index_item.html
{#首页加载更多#}
{% load staticfiles %}

{% for item in articles %}
    <div class="blogs" data-scroll-reveal="enter bottom over 1s">
        <h3 class="blogtitle">
            <a target="_blank" href="{% url 'blog:article_detail' item.unique_id %}">
                {{ item.title }}
            </a>
        </h3>
        <span class="blogpic">
                            <a target="_blank" href="{% url 'blog:article_detail' item.unique_id %}">
                                <img src="{% static item.pic.name %}" alt="">
                            </a>
                        </span>
        <p class="blogtext">{{ item.label }}</p>
        <div class="bloginfo">
            <ul>
                <li class="author">
                    <a href="{% url 'blog:author_info' item.author.unique_id %}" target="_blank">
                        {{ item.author.nickname }}
                    </a>
                </li>
                <li class="lmname">
                    <a href="{% url 'blog:article_list' 'type' item.type.unique_id %}"
                       target="_blank">{{ item.type.typename }}</a>
                </li>
                <li class="timer">{{ item.addtime }}</li>
                <li class="view"><span>{{ item.count }}</span>已阅读</li>
                <li class="like">{{ item.like }}</li>
            </ul>
        </div>
    </div>
{% empty %}
    <h1>文章已全部显示，没有新文章！</h1>
{% endfor %}

templates/blog/level1_article_list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    新码农-{{ name_name }}
{% endblock %}

{% block css %}
{% endblock %}

{% block main %}

    {#背景图#}
    <div class="pagebg sh"></div>
    {#背景图#}

    <div class="container">

        {% if messages %}
            <script>
                {% for msg in messages %}
                    alert('{{ msg.message }}');
                {% endfor %}
            </script>
        {% endif %}

        <h1 class="t_nav"><span>{{ name_label }}</span>
            <a href="/" class="n1">网站首页</a><a class="n2">{{ name_name }}</a>
        </h1>

        {#文章列表开始#}
        <div class="blogsbox">
            {% for item in page %}
                <div class="blogs" data-scroll-reveal="enter bottom over 1s">
                    <h3 class="blogtitle">
                        <a href="{% url 'blog:article_detail' item.unique_id %}" target="_blank">{{ item.title }}</a>
                    </h3>
                    <span class="blogpic">
                        <a href="{% url 'blog:article_detail' item.unique_id %}" title="{{ item.title }}"
                           target="_blank">
                        <img src="{% static item.pic.name %}" alt=""></a>
                    </span>
                    <p class="blogtext">{{ item.label }}</p>
                    <div class="bloginfo">
                        <ul>
                            <li class="author">
                                <a href="{% url 'blog:author_info' item.author.unique_id %}" target="_blank">
                                    {{ item.author.nickname }}
                                </a>
                            </li>
                            <li class="lmname">
                                <a href="{% url 'blog:article_list' 'type' item.type.unique_id %}" target="_blank">
                                    {{ item.type.typename }}
                                </a>
                            </li>
                            <li class="timer">{{ item.addtime }}</li>
                            <li class="view"><span>{{ item.count }}</span>&nbsp;已阅读</li>
                            <li class="like">{{ item.like }}</li>
                        </ul>
                    </div>
                </div>
            {% endfor %}

            {#分页#}
            <div class="pagelist">
                {#上一页#}
                {% if page.has_previous %}
                    <a href="{% url 'blog:article_list' word name_id page.previous_page_number %}">上一页</a>
                {% else %}
                    <span>上一页</span>
                {% endif %}
                {#上一页#}

                {#第一页#}
                {% if first %}
                    <a title="首页" href="{% url 'blog:article_list' word name_id 1 %}">1</a>
                {% endif %}
                {#第一页#}

                {#当前页左边连续的页码号#}
                {% if left %}
                    {% if left_has_more %}
                        <span>...</span>
                    {% endif %}
                    {% for i in left %}
                        <a href="{% url 'blog:article_list' word name_id i %}">{{ i }}</a>
                    {% endfor %}
                {% endif %}
                {#当前页左边连续的页码号#}

                {#当前页#}
                <a title="当前页" style="color: #6dbfff">{{ page_number }}</a>
                {#当前页#}

                {#当前页右边连续的页码号#}
                {% if right %}
                    {% for i in right %}
                        <a href="{% url 'blog:article_list' word name_id i %}">{{ i }}</a>
                    {% endfor %}
                    {% if right_has_more %}
                        <span>...</span>
                    {% endif %}
                {% endif %}
                {#当前页右边连续的页码号#}

                {#最后一页#}
                {% if last %}
                    <a title="尾页" href="{% url 'blog:article_list' word name_id total_pages %}">{{ total_pages }}</a>
                {% endif %}
                {#最后一页#}

                {#下一页#}
                {% if page.has_next %}
                    <a href="{% url 'blog:article_list' word name_id page.next_page_number %}">下一页</a>
                {% else %}
                    <span>下一页</span>
                {% endif %}
                {#下一页#}
            </div>
            {#分页#}

        </div>
        {#文章列表结束#}

        {#侧边栏#}
        {% include 'blog/base_sidebar_wz.html' %}
        {#侧边栏#}

    </div>
{% endblock %}

templates/blog/level1_leave_msg.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    新码农-留言板
{% endblock %}

{% block css %}
    <link href="{% static 'css/leave_msg.css' %}" rel="stylesheet">
    <script type="text/javascript" src="{% static 'ueditor/ueditor.config.js' %}"></script>
    <script type="text/javascript" src="{% static 'ueditor/ueditor.all.js' %}"></script>
    <script type="text/javascript" src="{% static 'ueditor/lang/zh-cn/zh-cn.js' %}"></script>
{% endblock %}

{% block main %}

    {#背景图#}
    <div class="pagebg ab"></div>
    {#背景图#}

    <div class="container">

        {% if messages %}
            <script>
                {% for msg in messages %}
                    alert('{{ msg.message }}');
                {% endfor %}
            </script>
        {% endif %}

        <h1 class="t_nav">
            <span>你，我生命中一个重要的过客，我们之所以是过客，因为你未曾会为我停留。</span>
            <a href="/" class="n1">网站首页</a><a class="n2">留言</a>
        </h1>
        <div class="news_infos">
            {% if not request.session.user_id %}
                <h2 class="dlts">请先
                    <a href="{% url 'user:sign_in' %}?next={{ request.path }}" target="_blank">
                        登录
                    </a>，才可参与留言！
                </h2>
            {% else %}
                <form method="post" action="{% url 'blog:leave_msg' %}">
                    {% csrf_token %}
                    <h2 class="nr">留言内容
                        <span style="font-size: 12px">（最长140字符，暂不支持上传图片和文件）</span>
                    </h2>
                    <textarea id="input_content" name="content"></textarea>
                    <p class="dasbox tjplp">
                        <input type="submit" value="提交留言" class="tjpl">
                    </p>
                </form>
            {% endif %}
            <h2 class="qbpl">全部留言( {{ msg_num }} )</h2>
            <div class="itemlist">
                {% for item in msgs %}
                    <div class="blogs zpl" data-scroll-reveal="enter bottom over 1s">
                    <span class="blogpic pltx">
                        <a href="{% url 'blog:author_info' item.user.id %}" target="_blank">
                            <img src="{% static item.user.photo.name %}">
                        </a>
                    </span>
                        <div class="blogtext plyh">
                            {{ item.user.nickname }} 留言于 {{ item.addtime }}
                        </div>
                        <div class="bloginfo plnr">
                            <p>
                                {% autoescape off %}
                                    {{ item.content | safe }}
                                {% endautoescape %}
                            </p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <script>
            var ue = UE.getEditor('input_content', {
                toolbars: [
                    ['emotion', 'link']
                ],
                initialFrameWidth: "99%",
                initialFrameHeight: "100",
            });
        </script>

        {#信息侧边栏#}
        {% include 'blog/base_sidebar_me.html' %}
        {#信息侧边栏#}

    </div>
{% endblock %}