apps/blog/urls.py
from django.urls import path

from apps.blog import views

urlpatterns = [
    # 首页加载更多
    path("more/<int:pagenum>/", views.more, name='more'),
    # 文章列表
    path('article_list/<str:key>/<str:unique_id>/', views.article_list, name='article_list'),
    path('article_list/<str:key>/<str:unique_id>/<int:num>/', views.article_list, name='article_list'),
    # 文章详情
    path('article_detail/<str:unique_id>/', views.article_detail, name='article_detail'),
    # 时间轴
    path('time_axis/', views.time_axis, name='time_axis'),
    # 关于我
    path('about_me/', views.about_me, name='about_me'),
    # 留言
    path('leave_msg/', views.leave_msg, name='leave_msg'),
    # 点赞
    path('like/<int:id>/', views.like, name='like'),
    # 评论
    path("comment/<str:unique_id>/", views.comment, name='comment'),
    path("comment/<str:unique_id>/<int:pid>/", views.comment, name='comment'),
    # 收藏
    path("article_col/<int:aid>/", views.article_col, name='article_col'),
    # 留言
    path("leave_msg/", views.leave_msg, name='leave_msg'),
    # 搜索
    path("search/", views.search, name='search'),
    # 作者信息
    path("author_info/<str:unique_id>/", views.author_info, name='author_info'),
]

apps/user/urls.py
from django.urls import path

from apps.user import views

urlpatterns = [
    # 注册
    path('sign_up/', views.sign_up, name='sign_up'),
    # 登陆
    path('sign_in/', views.sign_in, name='sign_in'),
    # 注销
    path('sign_out/', views.sign_out, name='sign_out'),
    # 用户中心
    path('user/<str:unique_id>/', views.user, name='user'),
    # 用户修改密码
    path('repwd/<str:unique_id>/', views.repwd, name='repwd'),
    # 用户评论记录
    path('comment/<str:unique_id>/', views.comment, name='comment'),
    # 用户删除评论记录
    path('comment_del/<str:unique_id>/', views.comment_del, name='comment_del'),
    # 用户收藏记录
    path('articlecol/<str:unique_id>/', views.articlecol, name='articlecol'),
    # 用户删除收藏记录
    path('articlecol_del/<str:unique_id>/', views.articlecol_del, name='articlecol_del'),
]

newcoder/urls.py
from django.contrib import admin
from django.urls import path, include

# 导入静态文件模块
from django.views.static import serve
# 导入配置文件里的文件上传配置
from django.conf import settings

from apps.blog import views

urlpatterns = [
    # 后台
    path('admin/', admin.site.urls),
    # 应用
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    # 首页
    path('', views.index),
    # 微信验证
    path('MP_verify_hC03z28vx2ij7bpL.txt', views.weixin_auth),
    # 配置富文本的URL
    path('summernote/', include('django_summernote.urls')),
    # 用于上传图片文件
    path('static/', serve, {'document_root': settings.MEDIA_ROOT}),
    # 用于加载静态文件
    path('static/', serve, {'document_root': settings.STATIC_ROOT}),
]

templates/base.html
<!doctype html>

{#导入静态文件#}
{% load staticfiles %}

<html>
<head>
    <meta charset="UTF-8">
    <title>
        {#本页标题#}
        {% block title %}
        {% endblock %}
        {#本页标题#}
    </title>
    <meta name="keywords" content="新码农,个人博客,技术分享"/>
    <meta name="description" content="新码农博客，是一个站在Python全栈开发之路的程序员个人网站。"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
    <link href="{% static 'css/m.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery.easyfader.min.js' %}"></script>
    <script src="{% static 'js/scrollReveal.js' %}"></script>
    <script src="{% static 'js/common.js' %}"></script>
    <!--[if lt IE 9]><script src="js/modernizr.js"></script><![endif]-->
    {#标题栏显示图标#}
    <link rel="icon" href="{% static 'images/logo_icon_.bmp' %}" type="image/x-icon">
    {#收藏夹显示图标#}
    <link rel="shortcut icon" href="{% static 'images/logo_icon_.bmp' %}" type="image/x-icon">

    {#其他css、js文件#}
    {% block css %}
    {% endblock %}
    {#其他css、js文件#}

    {#百度验证#}
    <meta name="baidu-site-verification" content="EQthgGmrll"/>
    {#百度验证#}
    {#百度自动推送#}
    <script>
        (function () {
            var bp = document.createElement('script');
            var curProtocol = window.location.protocol.split(':')[0];
            if (curProtocol === 'https') {
                bp.src = 'https://zz.bdstatic.com/linksubmit/push.js';
            } else {
                bp.src = 'http://push.zhanzhang.baidu.com/push.js';
            }
            var s = document.getElementsByTagName("script")[0];
            s.parentNode.insertBefore(bp, s);
        })();
    </script>
    {#百度自动推送#}

    {#360验证#}
    <meta name="360-site-verification" content="c9f567294481e8a370740518e910e408"/>
    {#360验证#}
    {#360自动推送#}
    <script>
        (function () {
            var src = (document.location.protocol == "http:") ? "http://js.passport.qihucdn.com/11.0.1.js?30525ee6206f84c31fb1000414bb6ceb" : "https://jspassport.ssl.qhimg.com/11.0.1.js?30525ee6206f84c31fb1000414bb6ceb";
            document.write('<script src="' + src + '" id="sozz"><\/script>');
        })();
    </script>
    {#360自动推送#}

</head>
<body>
{#网页头部开始#}
<header>

    {#导航开始#}
    <div class="menu">
        <nav class="nav" id="topnav">
            <h1 class="logo">
                <a href="/">
                    <img src="{% static 'images/logo_index.jpg' %}"
                         style="height: 70px;width: 70px;margin-top: 5px;border-radius: 50%">
                </a>
            </h1>
            <li style="margin-left: -70px"><a href="/">网站首页</a></li>
            <li>
                <a href="{% url 'blog:article_list' 'type' type_1.unique_id %}">心情随笔</a>
                <ul class="sub-nav">
                    {% for tag in tags_1 %}
                        <li><a href="{% url 'blog:article_list' 'tag' tag.unique_id %}">{{ tag.tagname }}</a></li>
                    {% endfor %}
                    <li><a href="{% url 'blog:article_list' 'type' type_1.unique_id %}">全部</a></li>
                </ul>
            </li>
            <li>
                <a href="{% url 'blog:article_list' 'type' type_2.unique_id %}">时事点评</a>
                <ul class="sub-nav">
                    {% for tag in tags_2 %}
                        <li><a href="{% url 'blog:article_list' 'tag' tag.unique_id %}">{{ tag.tagname }}</a></li>
                    {% endfor %}
                    <li><a href="{% url 'blog:article_list' 'type' type_2.unique_id %}">全部</a></li>
                </ul>
            </li>
            <li>
                <a href="{% url 'blog:article_list' 'type' type_3.unique_id %}">技术分享</a>
                <ul class="sub-nav">
                    {% for tag in tags_3 %}
                        <li><a href="{% url 'blog:article_list' 'tag' tag.unique_id %}">{{ tag.tagname }}</a></li>
                    {% endfor %}
                    <li><a href="{% url 'blog:article_list' 'type' type_3.unique_id %}">全部</a></li>
                </ul>
            </li>
            <li><a href="{% url 'blog:time_axis' %}">时间轴</a></li>
            <li><a href="{% url 'blog:about_me' %}">关于我</a></li>
            <li style="margin-right: 40px"><a href="{% url 'blog:leave_msg' %}">留言板</a></li>
            {% if not request.session.user_id %}
                <li><a href="{% url 'user:sign_up' %}">注册</a></li>
                <li><a href="{% url 'user:sign_in' %}">登陆</a></li>
            {% else %}
                <li>
                    <a href="{% url 'user:user' request.session.user_id %}">
                        <img src="{% static request.session.user_photo %}"
                             style="height: 40px;width: 40px;margin-top: 20px;border-radius: 50%">
                    </a>
                </li>
                <li><a href="{% url 'user:sign_out' %}">退出账号</a></li>
            {% endif %}
            {#搜索开始#}
            <div id="search_bar" class="search_bar">
                <form id="searchform" action="{% url 'blog:search' %}" method="post" name="searchform">
                    {% csrf_token %}
                    <input class="input" placeholder="想搜点什么呢..." type="text" name="keyboard" id="keyboard">
                    <input type="hidden" name="show" value="title"/>
                    <input type="hidden" name="tempid" value="1"/>
                    <input type="hidden" name="tbname" value="news">
                    <input type="hidden" name="Submit" value="搜索"/>
                    <span class="search_ico"></span>
                </form>
            </div>
            {#搜索结束#}
        </nav>
    </div>
    {#导航结束#}

    {#导航移动端开始#}
    <div id="mnav">
        <h2><a href="/" class="mlogo">新码农博客</a><span class="navicon"></span></h2>
        <dl class="list_dl">
            <dt class="list_dt"><a href="/">网站首页</a></dt>
            <dt class="list_dt"><a href="#">心情随笔</a></dt>
            <dd class="list_dd">
                <ul>
                    {% for tag in tags_1 %}
                        <li><a href="{% url 'blog:article_list' 'tag' tag.unique_id %}">{{ tag.tagname }}</a></li>
                    {% endfor %}
                    <li><a href="{% url 'blog:article_list' 'type' type_1.unique_id %}">全部</a></li>
                </ul>
            </dd>
            <dt class="list_dt"><a href="#">时事点评</a></dt>
            <dd class="list_dd">
                <ul>
                    {% for tag in tags_2 %}
                        <li><a href="{% url 'blog:article_list' 'tag' tag.unique_id %}">{{ tag.tagname }}</a></li>
                    {% endfor %}
                    <li><a href="{% url 'blog:article_list' 'type' type_2.unique_id %}">全部</a></li>
                </ul>
            </dd>
            <dt class="list_dt"><a href="#">技术分享</a></dt>
            <dd class="list_dd">
                <ul>
                    {% for tag in tags_3 %}
                        <li><a href="{% url 'blog:article_list' 'tag' tag.unique_id %}">{{ tag.tagname }}</a></li>
                    {% endfor %}
                    <li><a href="{% url 'blog:article_list' 'type' type_3.unique_id %}">全部</a></li>
                </ul>
            </dd>
            <dt class="list_dt"><a href="{% url 'blog:time_axis' %}">时间轴</a></dt>
            <dt class="list_dt"><a href="{% url 'blog:about_me' %}">关于我</a></dt>
            <dt class="list_dt"><a href="{% url 'blog:leave_msg' %}">留言板</a></dt>
            {% if not request.session.user_id %}
                <dt class="list_dt"><a href="{% url 'user:sign_up' %}">注册</a></dt>
                <dt class="list_dt"><a href="{% url 'user:sign_in' %}">登陆</a></dt>
            {% else %}
                <dt class="list_dt">
                    <a href="{% url 'user:user' request.session.user_id %}">
                        <img src="{% static request.session.user_photo %}"
                             style="height: 40px;width: 40px;margin-top: 20px;border-radius: 50%">
                    </a>
                </dt>
                <dt class="list_dt"><a href="{% url 'user:sign_out' %}">退出账号</a></dt>
            {% endif %}
        </dl>
    </div>
    {#导航移动端结束#}

</header>
{#网页头部结束#}

{#内容主体开始#}
{% block main %}

{% endblock %}
{#内容主体结束#}

{#网页底部开始#}
<footer>
    <p>
        <strong>Copyright &copy; 2019-2029</strong> |
        <a href="/admin" target="_blank">All Rights Reserved</a> |
        <a href="/" target="_blank">newcoder.top</a> |
        <a href="http://www.beian.miit.gov.cn" target="_blank">冀ICP备18036301号-1</a>
    </p>
    <a href="#" class="cd-top">Top</a>
</footer>
{#网页底部结束#}

</body>
</html>