apps/blog/urls.py
from django.urls import path

from apps.blog import views

urlpatterns = [
    # 首页加载更多
    path("more/<int:pagenum>/", views.more, name='more'),
    # 文章列表
    path('article_list/<str:key>/<str:unique_id>/', views.article_list, name='article_list'),
    path('article_list/<str:key>/<str:unique_id>/<int:num>/', views.article_list, name='article_list'),
    # 文章详情
    path('article_detail/<str:unique_id>/', views.article_detail, name='article_detail'),
    # 时间轴
    path('time_axis/', views.time_axis, name='time_axis'),
    # 关于我
    path('about_me/', views.about_me, name='about_me'),
    # 留言
    path('leave_msg/', views.leave_msg, name='leave_msg'),
    # 点赞
    path('like/<int:id>/', views.like, name='like'),
    # 评论
    path("comment/<str:unique_id>/", views.comment, name='comment'),
    path("comment/<str:unique_id>/<int:pid>/", views.comment, name='comment'),
    # 收藏
    path("article_col/<int:aid>/", views.article_col, name='article_col'),
    # 留言
    path("leave_msg/", views.leave_msg, name='leave_msg'),
    # 搜索
    path("search/", views.search, name='search'),
    # 作者信息
    path("author_info/<str:unique_id>/", views.author_info, name='author_info'),
]

apps/user/urls.py
from django.urls import path

from apps.user import views

urlpatterns = [
    # 注册
    path('sign_up/', views.sign_up, name='sign_up'),
    # 登陆
    path('sign_in/', views.sign_in, name='sign_in'),
    # 注销
    path('sign_out/', views.sign_out, name='sign_out'),
    # 用户中心
    path('user/<str:unique_id>/', views.user, name='user'),
    # 用户修改密码
    path('repwd/<str:unique_id>/', views.repwd, name='repwd'),
    # 用户评论记录
    path('comment/<str:unique_id>/', views.comment, name='comment'),
    # 用户删除评论记录
    path('comment_del/<str:unique_id>/', views.comment_del, name='comment_del'),
    # 用户收藏记录
    path('articlecol/<str:unique_id>/', views.articlecol, name='articlecol'),
    # 用户删除收藏记录
    path('articlecol_del/<str:unique_id>/', views.articlecol_del, name='articlecol_del'),
]

newcoder/urls.py
from django.contrib import admin
from django.urls import path, include

# 导入静态文件模块
from django.views.static import serve
# 导入配置文件里的文件上传配置
from django.conf import settings

from apps.blog import views

urlpatterns = [
    # 后台
    path('admin/', admin.site.urls),
    # 应用
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    # 首页
    path('', views.index),
    # 微信验证
    path('MP_verify_hC03z28vx2ij7bpL.txt', views.weixin_auth),
    # 配置富文本的URL
    path('summernote/', include('django_summernote.urls')),
    # 用于上传图片文件
    path('static/', serve, {'document_root': settings.MEDIA_ROOT}),
    # 用于加载静态文件
    path('static/', serve, {'document_root': settings.STATIC_ROOT}),
]

apps/user/models.py
from shortuuid import ShortUUID

from django.db import models
from django.contrib.auth.models import AbstractUser


# 生成8位唯一标识符
class NewUUID(ShortUUID):
    def __init__(self, alphabet=None):
        if alphabet is None:
            alphabet = 'abcdefghijklmnopqrstuvwxyz0123456789'
        super().__init__(alphabet)


# 用户表
class User(AbstractUser):
    nickname = models.CharField(max_length=16, unique=True, null=True, blank=True, verbose_name='昵称')
    birthday = models.DateField(null=True, blank=True, verbose_name="出生年月")
    # 0为男，1为女
    gender = models.IntegerField(choices=((0, "男"), (1, "女")), default=0, verbose_name="性别")
    photo = models.ImageField(upload_to="user/photo", null=True, blank=True, verbose_name='头像')
    phone = models.CharField(max_length=11, unique=True, null=True, blank=True, verbose_name='手机号')
    email = models.EmailField(max_length=100, unique=True, null=True, blank=True, verbose_name='邮箱')
    desc = models.CharField(max_length=140, null=True, blank=True, verbose_name='个人简介')
    addtime = models.DateField(auto_now_add=True, verbose_name='注册日期')
    unique_id = models.CharField(max_length=36, default=NewUUID().random(8), unique=True, verbose_name='唯一标识符')

    class Meta:
        # 指定在admin管理界面中显示中文,表示单数形式的显示
        verbose_name = '用户表'
        # 指定在admin管理界面中显示中文,表示复数形式的显示
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.username


# 用户留言表
class Leavemsg(models.Model):
    content = models.CharField(max_length=140, verbose_name="用户留言")
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='留言用户')
    addtime = models.DateTimeField(auto_now_add=True, verbose_name='留言时间')
    unique_id = models.CharField(max_length=36, default=NewUUID().random(8), unique=True, verbose_name='唯一标识符')

    class Meta:
        verbose_name = '用户留言表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.user.nickname

apps/user/forms.py
from django import forms


# 注册验证
class SignupForm(forms.Form):
    username = forms.CharField(max_length=16, min_length=6,
                               error_messages={'required': '用户名不能为空', 'min_length': '用户名长度至少6位'})
    nickname = forms.CharField(max_length=16, min_length=2,
                               error_messages={'required': '昵称不能为空', 'min_length': '用户名长度至少2位'})
    password = forms.CharField(max_length=64, min_length=6,
                               error_messages={'required': '密码不能为空', 'min_length': '密码长度至少6位'})
    photo = forms.ImageField(error_messages={'required': '没有选择图片'})


# 登陆验证
class LoginForm(forms.Form):
    username = forms.CharField(max_length=20, min_length=3,
                               error_messages={'required': '用户名不能为空', 'min_length': '用户名长度至少3位'})
    password = forms.CharField(max_length=64, min_length=6,
                               error_messages={'required': '密码不能为空', 'min_length': '密码长度至少6位'})

apps/user/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.hashers import make_password, check_password
from django.db.models.query_utils import Q
from django.contrib import messages

from user.models import *
from blog.models import *
from user.forms import SignupForm, LoginForm


# 验证登陆装饰器
def user_login_req(func):
    def inner(request, *args, **kwargs):
        obj = request.session.get('user_id')
        if obj:
            # 已经登录
            return func(request, *args, **kwargs)
        else:
            # 没有登录
            # 判断发送的请求是不是ajax
            # 如果是ajax，则返回一个redirect字符串
            # 表示是一个ajax请求
            if 'XMLHttpRequest' == request.META.get('HTTP_X_REQUESTED_WITH'):
                return HttpResponse('请登录')
            else:
                # 不是ajax请求，是浏览器发送的请求，正常返回登录
                messages.success(request, "请先登录！！！")
                return redirect('/user/sign_in/')

    return inner


# 验证当前用户权限装饰器，当前用户只能操作自己信息
def user_auth_req(func):
    def auth(request, *args, **kwargs):
        user_session = request.session.get('user_id')
        user_info = request.path[-9:-1]
        if user_session == user_info:
            return func(request, *args, **kwargs)
        else:
            messages.success(request, '没有访问当前页面权限！！！')
            return redirect("/user/user/{}/".format(user_session))

    return auth


# 注册
def sign_up(request):
    if request.method == "GET":
        return render(request, 'user/level0_sign_up.html', locals())
    if request.method == 'POST':
        f = SignupForm(request.POST, request.FILES)
        if f.is_valid():
            count = User.objects.filter(username=f.cleaned_data["username"]).count()
            if count > 0:
                return render(request, 'user/level0_sign_up.html', {'msg': '用户名已经存在', 'data': f.data})
            count1 = User.objects.filter(nickname=f.cleaned_data["nickname"]).count()
            if count1 > 0:
                return render(request, 'user/level0_sign_up.html', {'msg': '昵称已经存在', 'data': f.data})
            if f.data['password'] != f.data['password1']:
                return render(request, 'user/level0_sign_up.html', {'msg': '两次密码不一样', 'data': f.data})
            cleandata = f.cleaned_data
            cleandata['password'] = make_password(cleandata['password'])
            User.objects.create(**cleandata)
            messages.success(request, '注册成功')
            return redirect("/user/sign_in/")
        else:
            return render(request, 'user/level0_sign_up.html', {'errors': f.errors, 'data': f.data})


# 登陆
def sign_in(request):
    if request.method == 'GET':
        next = request.GET.get('next', '')
        username = ''
        if request.session.get('save'):
            username = request.COOKIES.get('username')
        return render(request, "user/level0_sign_in.html", locals())
    if request.method == 'POST':
        username = request.POST.get("username")
        save = request.POST.get("save")
        f = LoginForm(request.POST)
        next = request.POST.get('next', '')
        if f.is_valid():
            user = User.objects.filter(
                Q(username=f.cleaned_data['username']) | Q(phone=f.cleaned_data['username'])).first()
            if user:
                if check_password(f.cleaned_data['password'], user.password):
                    request.session['user_id'] = user.unique_id
                    request.session['user_username'] = user.nickname
                    request.session['user_photo'] = user.photo.name
                    request.session['save'] = 0
                    if next == '':
                        response = redirect('/')
                    else:
                        response = redirect(next)
                    response.set_cookie('username', user.username, 3600)
                    if save:
                        request.session['save'] = 1
                    return response
                else:
                    return render(request, 'user/level0_sign_in.html', {'msg': '用户名或密码错误', 'data': f.data})
            else:
                return render(request, 'user/level0_sign_in.html', {'msg': '用户名不存在', 'data': f.data})
        else:
            return render(request, "user/level0_sign_in.html", {"errors": f.errors, "data": f.data})
    return render(request, "user/level0_sign_in.html", locals())


# 注销
@user_login_req
def sign_out(request):
    # 清空session存储的数据
    request.session.flush()
    # 清空cookie存储的数据
    response = redirect('/')
    response.delete_cookie('username')
    return redirect('/')


# 用户中心
@user_login_req
@user_auth_req
def user(request, unique_id):
    user = User.objects.get(unique_id=unique_id)
    uid = user.id
    if request.method == 'POST':
        # 昵称修改
        nickname = request.POST.get('nickname', '')
        if nickname == user.nickname:
            pass
        else:
            if User.objects.filter(nickname=nickname).count() > 0:
                messages.success(request, '昵称已被使用')
                return redirect("/user/user/{}/".format(unique_id))
            else:
                user.nickname = nickname
                user.save()
        # 生日修改
        birthday = request.POST.get('birthday', '')
        if birthday == user.birthday:
            pass
        else:
            user.birthday = birthday
            user.save()
        # 性别修改
        gender = request.POST.get('gender', '')
        if gender == user.gender:
            pass
        else:
            user.gender = gender
            user.save()
        # 头像修改
        photo = request.FILES.get('photo', '')
        if photo:
            if ('user/photo/' + photo.name) == user.photo.name:
                pass
            else:
                User.objects.update_or_create({"photo": photo}, id=uid)
        else:
            pass
        # 手机号修改
        phone = request.POST.get('phone', '')
        if phone == user.phone:
            pass
        else:
            if User.objects.filter(phone=phone).count() > 0:
                messages.success(request, '手机号已被使用')
                return redirect("/user/user/{}/".format(unique_id))
            else:
                user.phone = phone
                user.save()
        # 邮箱修改
        email = request.POST.get('email', '')
        if email == user.email:
            pass
        else:
            if User.objects.filter(email=email).count() > 0:
                messages.success(request, '邮箱已被使用')
                return redirect("/user/user/{}/".format(unique_id))
            else:
                user.email = email
                user.save()
        # 简介修改
        desc = request.POST.get('desc', '')
        if desc == user.desc:
            pass
        else:
            user.desc = desc
            user.save()
        messages.success(request, '成功保存')
        return redirect("/user/user/{}/".format(unique_id))
    return render(request, "user/level1_user.html", locals())


# 用户修改密码
@user_login_req
@user_auth_req
def repwd(request, unique_id):
    user = User.objects.get(unique_id=unique_id)
    if request.method == 'POST':
        password_old = request.POST.get('password_old', '')
        password_new = request.POST.get('password_new', '')
        password_new2 = request.POST.get('password_new2', '')
        if check_password(password_old, user.password):
            if password_new == password_new2:
                user.password = make_password(password_new)
                user.save()
                messages.success(request, '修改成功')
                return redirect("/user/repwd/{}/".format(unique_id))
            else:
                messages.success(request, '两次密码不一致')
        else:
            messages.success(request, '旧密码不正确')
    return render(request, 'user/level1_repwd.html', locals())


# 用户评论记录
@user_login_req
@user_auth_req
def comment(request, unique_id):
    user = User.objects.get(unique_id=unique_id)
    comments = Comment.objects.filter(user=user)
    return render(request, 'user/level1_comment.html', locals())


# 用户删除评论记录
@user_login_req
@user_auth_req
def comment_del(request, unique_id):
    uid = request.session.get('user_id')
    comment = Comment.objects.get(unique_id=unique_id)
    comment.delete()
    return redirect("/user/comment/{}/".format(uid))


# 用户收藏记录
@user_login_req
@user_auth_req
def articlecol(request, unique_id):
    user = User.objects.get(unique_id=unique_id)
    articlecols = Articlecol.objects.filter(user=user)
    return render(request, 'user/level1_articlecol.html', locals())


# 用户删除收藏记录
@user_login_req
@user_auth_req
def articlecol_del(request, unique_id):
    uid = request.session.get('user_id')
    articlecol = Articlecol.objects.get(unique_id=unique_id)
    articlecol.delete()
    return redirect("/user/articlecol/{}/".format(uid))

templates/user/level0_sign_in.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    新码农-登陆
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/sign_in.css' %}">
{% endblock %}

{% block main %}
    <article>

        {% if messages %}
            <script>
                {% for msg in messages %}
                    alert('{{ msg.message }}');
                {% endfor %}
            </script>
        {% endif %}

        <div class="signin">
            <h2>
                <p>
                    <span>账号密码登陆</span>
                    <a href="{% url 'user:sign_up' %}">注册新用户</a>
                </p>
            </h2>

            <form method="post" action="{% url 'user:sign_in' %}" enctype="multipart/form-data">
                {% csrf_token %}
                <p style="margin-left: 450px;color: red">{{ msg }}</p>
                <table>
                    <tr>
                        <td>请输入用户名</td>
                        <td>
                            <input type="text" name="username" value="{{ username }}">
                        </td>
                        <td>{{ errors.username.0 }}</td>
                    </tr>
                    <tr>
                        <td>请输入密码</td>
                        <td>
                            <input type="password" name="password" value="{{ data.password }}">
                        </td>
                        <td>{{ errors.password.0 }}</td>
                    </tr>
                    <tr>
                        <td colspan="3">
                            <input type="checkbox" name="save" value="1" class="checkbox"
                                   {% if username %}checked{% endif %}>记住用户名
                        </td>
                    </tr>
                    <tr>
                        <input name="next" value="{{ next }}" hidden>
                        <td colspan="3"><input type="submit" value="登陆" class="signin_niu"></td>
                    </tr>
                </table>
            </form>

        </div>

        {#背景图#}
        <div class="blank"></div>
        {#背景图#}

    </article>
{% endblock %}

templates/user/level0_sign_up.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    新码农-注册
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/sign_up.css' %}">
{% endblock %}

{% block main %}
    <article>

        {% if messages %}
            <script>
                {% for msg in messages %}
                    alert('{{ msg.message }}');
                {% endfor %}
            </script>
        {% endif %}

        <div class="signup">
            <h2>
                <p>
                    <span>注册新码农，让编程更简单</span>
                    <a href="{% url 'user:sign_in' %}">使用已有账号登陆</a>
                </p>
            </h2>

            <form method="post" action="{% url 'user:sign_up' %}" enctype="multipart/form-data">
                {% csrf_token %}
                <p style="margin-left: 450px;color: red">{{ msg }}</p>
                <table>
                    <tr>
                        <td>请输入用户名</td>
                        <td>
                            <input type="text" name="username" value="{{ data.username }}">
                        </td>
                        <td>{{ errors.username.0 }}</td>
                    </tr>
                    <tr>
                        <td>请输入昵称</td>
                        <td>
                            <input type="text" name="nickname" value="{{ data.nickname }}">
                        </td>
                        <td>{{ errors.nickname.0 }}</td>
                    </tr>
                    <tr>
                        <td>请输入密码</td>
                        <td>
                            <input type="password" name="password" value="{{ data.password }}">
                        </td>
                        <td>{{ errors.password.0 }}</td>
                    </tr>
                    <tr>
                        <td>请再次输入密码</td>
                        <td>
                            <input type="password" name="password1">
                        </td>
                        <td>{{ errors.password.0 }}</td>
                    </tr>
                    <tr>
                        <td>头像上传</td>
                        <td>
                            <input type="file" name="photo">
                        </td>
                        <td>{{ errors.photo.0 }}</td>
                    </tr>
                    <tr>
                        <td colspan="3"><input type="submit" value="注册" class="signup_niu"></td>
                    </tr>
                </table>
            </form>

        </div>

        {#背景图#}
        <div class="blank"></div>
        {#背景图#}

    </article>
{% endblock %}

templates/user/level1_articlecol.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    新码农-收藏记录
{% endblock %}

{% block css %}
    <link href="{% static 'css/comment.css' %}" rel="stylesheet">
{% endblock %}

{% block main %}
    <article>

        {% if messages %}
            <script>
                {% for msg in messages %}
                    alert('{{ msg.message }}');
                {% endfor %}
            </script>
        {% endif %}

        <div class="news_pl">
            {#会员侧边栏#}
            {% include 'user/level1_user_menu.html' %}
            {#会员侧边栏#}
            <h3>收藏记录</h3>
            <div class="itemlist">
                {% for item in articlecols %}
                    <div class="blogs zpl" style="width: 600px">
                        <span class="blogpic pltx">
                                <img src="{% static item.user.photo.name %}" style="width: 50px;height: 50px">
                        </span>
                        <div class="blogtext plyh">
                            收藏
                            <a target="_blank"
                               href="{% url 'blog:article_detail' item.article.unique_id %}">
                                {{ item.article.title }}
                            </a>
                            于 {{ item.addtime }}
                        </div>
                        <div class="bloginfo plnr">
                            <p>
                                {% autoescape off %}
                                    {{ item.content | safe }}
                                {% endautoescape %}
                            </p>
                        </div>
                        <a href="{% url 'user:articlecol_del' item.unique_id %}">删除</a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </article>
{% endblock %}

templates/user/level1_comment.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    新码农-评论记录
{% endblock %}

{% block css %}
    <link href="{% static 'css/comment.css' %}" rel="stylesheet">
{% endblock %}

{% block main %}
    <article>

        {% if messages %}
            <script>
                {% for msg in messages %}
                    alert('{{ msg.message }}');
                {% endfor %}
            </script>
        {% endif %}

        <div class="news_pl">
            {#会员侧边栏#}
            {% include 'user/level1_user_menu.html' %}
            {#会员侧边栏#}
            <h3>评论记录</h3>
            <div class="itemlist">
                {% for item in comments %}
                    <div class="blogs zpl" style="width: 600px">
                    <span class="blogpic pltx">
                        <a href="">
                            <img src="{% static item.user.photo.name %}" style="width: 50px;height: 50px">
                        </a>
                    </span>
                        <div class="blogtext plyh">
                            评论
                            <a target="_blank"
                               href="{% url 'blog:article_detail' item.article.unique_id %}">
                                {{ item.article.title }}
                            </a>
                            于 {{ item.addtime }}
                        </div>
                        <div class="bloginfo plnr">
                            <p>
                                {% autoescape off %}
                                    {{ item.content | safe }}
                                {% endautoescape %}
                            </p>
                        </div>
                        <a href="{% url 'user:comment_del' item.unique_id %}">删除</a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </article>
{% endblock %}

templates/user/level1_repwd.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    新码农-修改密码
{% endblock %}

{% block css %}
{% endblock %}

{% block main %}
    <article>

        {% if messages %}
            <script>
                {% for msg in messages %}
                    alert('{{ msg.message }}');
                {% endfor %}
            </script>
        {% endif %}

        <div class="picsbox">

            {#会员侧边栏#}
            {% include 'user/level1_user_menu.html' %}
            {#会员侧边栏#}

            <h3>修改密码</h3>
            <form method="post" enctype="multipart/form-data" action="{% url 'user:repwd' user.unique_id %}">
                {% csrf_token %}
                <table>
                    <tr>
                        <td>原密码</td>
                        <td colspan="2"><input type="password" name="password_old" placeholder="输入旧密码" required></td>
                    </tr>
                    <tr>
                        <td>新密码</td>
                        <td colspan="2"><input type="password" name="password_new" placeholder="输入新密码" required></td>
                    </tr>
                    <tr>
                        <td>确认新密码</td>
                        <td colspan="2"><input type="password" name="password_new2" placeholder="确认新密码" required>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="3"><input type="submit" value="修改"></td>
                    </tr>
                </table>
            </form>
        </div>
    </article>
{% endblock %}

templates/user/level1_user.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    新码农-用户中心
{% endblock %}

{% block css %}
{% endblock %}

{% block main %}
    <article>

        {% if messages %}
            <script>
                {% for msg in messages %}
                    alert('{{ msg.message }}');
                {% endfor %}
            </script>
        {% endif %}

        <div class="picsbox">

            {#会员侧边栏#}
            {% include 'user/level1_user_menu.html' %}
            {#会员侧边栏#}

            <h3>用户中心</h3>
            <form method="post" enctype="multipart/form-data" action="{% url 'user:user' user.unique_id %}">
                {% csrf_token %}
                <table>
                    <tr>
                        <td>用户名</td>
                        <td><input type="text" name="username" value="{{ user.username }}" disabled></td>
                    </tr>
                    <tr>
                        <td>昵称</td>
                        <td><input type="text" name="nickname" value="{{ user.nickname }}"></td>
                    </tr>
                    <tr>
                        <td>性别</td>
                        <td>
                            {% if user.gender == 0 %}
                                <input type="radio" name="gender" value="0" checked/> 男
                                <input type="radio" name="gender" value="1"/> 女
                            {% elif user.gender == 1 %}
                                <input type="radio" name="gender" value="0"/> 男
                                <input type="radio" name="gender" value="1" checked/> 女
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td>邮箱</td>
                        <td><input type="email" name="email" value="{{ user.email }}"></td>
                    </tr>
                    <tr>
                        <td>手机号</td>
                        <td><input type="text" name="phone" value="{{ user.phone }}"></td>
                    </tr>
                    <tr>
                        <td>出生年月</td>
                        <td><input type="date" name="birthday" value="{{ user.birthday | safe }}"></td>
                    </tr>
                    <tr>
                        <td>头像</td>
                        <td>
                            <img src="{% static user.photo.name %}"
                                 style="height: 40px;width: 40px;margin-top: 20px;border-radius: 50%">
                            <input type="file" name="photo">
                        </td>
                    </tr>
                    <tr>
                        <td>个人简介</td>
                        <td><input type="text" name="desc" value="{{ user.desc }}"></td>
                    </tr>
                    <tr>
                        <td colspan="2"><input type="submit" value="保存"></td>
                    </tr>
                </table>
            </form>
        </div>
    </article>
{% endblock %}

templates/user/level1_user_menu.html
{% load staticfiles %}

<div class="sidebar">
    <div class="tuijian">
        <ul class="sidenews">
            <li>
                <p><a href="{% url 'user:user' user.unique_id %}">用户中心</a></p>
            </li>
            <li>
                <p><a href="{% url 'user:repwd' user.unique_id %}">修改密码</a></p>
            </li>
            <li>
                <p><a href="{% url 'user:comment' user.unique_id %}">评论记录</a></p>
            </li>
            <li>
                <p><a href="{% url 'user:articlecol' user.unique_id %}">收藏文章</a></p>
            </li>
        </ul>
    </div>
</div>